"""Masterの事実関係と判断データを分離する。

`investment_target.is_active` は実際には監視対象かどうかを表していたため、
`is_monitored` へ改名する。

テーマと銘柄の対応は上書きせず、有効期間を持つmembershipとして保存する。
`basket_weight` と `rationale` は配分・評価に属し、Masterの所属関係ではないため
移行しない。Assessment / Decisionの設計確定後に、versionとactorを持つ別テーブルで
扱う。

Revision ID: 0003_master_schema_boundaries
Revises: 0002_drop_observed_tables
"""

from alembic import op

revision = "0003_master_schema_boundaries"
down_revision = "0002_drop_observed_tables"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE investment_target RENAME COLUMN is_active TO is_monitored")
    op.execute("ALTER TABLE theme_investment_target RENAME TO theme_investment_target_legacy")
    op.execute("""
        CREATE TABLE theme_investment_target (
            membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            theme_id BIGINT NOT NULL REFERENCES theme(theme_id),
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            effective_to TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CHECK(effective_to IS NULL OR effective_to >= effective_from)
        )
    """)
    op.execute("""
        INSERT INTO theme_investment_target (
            theme_id, target_id, effective_from, effective_to, created_at, updated_at
        )
        SELECT
            theme_id,
            target_id,
            created_at,
            CASE WHEN is_active THEN NULL ELSE updated_at END,
            created_at,
            updated_at
        FROM theme_investment_target_legacy
    """)
    op.execute("DROP TABLE theme_investment_target_legacy")
    op.execute("""
        CREATE UNIQUE INDEX uq_theme_target_current_membership
        ON theme_investment_target(theme_id, target_id)
        WHERE effective_to IS NULL
    """)
    op.execute("""
        CREATE INDEX idx_theme_target_membership_history
        ON theme_investment_target(theme_id, target_id, effective_from)
    """)


def downgrade() -> None:
    raise NotImplementedError(
        "判断データをMasterへ戻すdowngradeは提供しません。"
        "必要なら0002時点へ復元し、バックアップから再構築してください"
    )
