"""Add versioned objectives and target allocation.

Objective is the capital-allocation and outcome-measurement context.
Theme remains an independent analytical classification of investment targets.

Revision ID: 0004_objective_allocation
Revises: 0003_master_schema_boundaries
"""

from alembic import op

revision = "0004_objective_allocation"
down_revision = "0003_master_schema_boundaries"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE objective (
            objective_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            objective_key TEXT NOT NULL UNIQUE,
            objective_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'draft'
                CHECK(status IN ('draft', 'active', 'paused', 'retired')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE TABLE objective_version (
            objective_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            objective_id BIGINT NOT NULL REFERENCES objective(objective_id),
            version_no INTEGER NOT NULL CHECK(version_no > 0),
            purpose TEXT NOT NULL,
            budget_amount NUMERIC(20, 2) NOT NULL CHECK(budget_amount >= 0),
            currency TEXT NOT NULL,
            target_return DOUBLE PRECISION,
            max_drawdown DOUBLE PRECISION
                CHECK(max_drawdown IS NULL OR (max_drawdown >= -1 AND max_drawdown <= 0)),
            investment_horizon TEXT,
            execution_mode TEXT NOT NULL DEFAULT 'live'
                CHECK(execution_mode IN ('live', 'paper')),
            valid_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            valid_to TIMESTAMPTZ,
            change_reason TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(objective_id, version_no),
            CHECK(valid_to IS NULL OR valid_to >= valid_from)
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_objective_current_version
        ON objective_version(objective_id)
        WHERE valid_to IS NULL
    """)
    op.execute("""
        CREATE TABLE objective_investment_target (
            objective_investment_target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            objective_version_id BIGINT NOT NULL
                REFERENCES objective_version(objective_version_id) ON DELETE CASCADE,
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            target_weight DOUBLE PRECISION NOT NULL
                CHECK(target_weight >= 0 AND target_weight <= 1),
            budget_cap NUMERIC(20, 2) CHECK(budget_cap IS NULL OR budget_cap >= 0),
            rationale TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(objective_version_id, target_id)
        )
    """)
    op.execute("""
        CREATE INDEX idx_objective_target_target
        ON objective_investment_target(target_id)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS objective_investment_target")
    op.execute("DROP TABLE IF EXISTS objective_version")
    op.execute("DROP TABLE IF EXISTS objective")
