"""Replace the provisional Objective model with capital allocation mandates.

Objective data was created only for schema prototyping and is intentionally not
migrated. The stable Investment Target and Theme masters are preserved.

Revision ID: 0005_capital_allocation_mandate
Revises: 0004_objective_allocation
"""

from alembic import op

revision = "0005_capital_allocation_mandate"
down_revision = "0004_objective_allocation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS objective_investment_target")
    op.execute("DROP TABLE IF EXISTS objective_version")
    op.execute("DROP TABLE IF EXISTS objective")
    op.execute("""
        CREATE TABLE capital_allocation_mandate (
            mandate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mandate_key TEXT NOT NULL UNIQUE,
            mandate_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'draft'
                CHECK(status IN ('draft', 'active', 'suspended', 'retired')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE TABLE mandate_version (
            mandate_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mandate_id BIGINT NOT NULL REFERENCES capital_allocation_mandate(mandate_id),
            version_no INTEGER NOT NULL CHECK(version_no > 0),
            purpose TEXT NOT NULL,
            budget_amount NUMERIC(20, 2) CHECK(budget_amount IS NULL OR budget_amount >= 0),
            currency TEXT CHECK(currency IS NULL OR char_length(currency) = 3),
            expected_return DOUBLE PRECISION,
            max_drawdown DOUBLE PRECISION
                CHECK(max_drawdown IS NULL OR (max_drawdown >= -1 AND max_drawdown <= 0)),
            horizon_months INTEGER CHECK(horizon_months IS NULL OR horizon_months > 0),
            benchmark_target_id BIGINT REFERENCES investment_target(target_id),
            review_cycle TEXT,
            next_review_at DATE,
            effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            effective_until TIMESTAMPTZ,
            change_reason TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(mandate_id, version_no),
            CHECK(effective_until IS NULL OR effective_until >= effective_from)
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_mandate_current_version
        ON mandate_version(mandate_id) WHERE effective_until IS NULL
    """)
    op.execute("""
        CREATE TABLE mandate_target_assignment (
            assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mandate_version_id BIGINT NOT NULL
                REFERENCES mandate_version(mandate_version_id) ON DELETE CASCADE,
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            status TEXT NOT NULL DEFAULT 'active'
                CHECK(status IN ('draft', 'active', 'suspended', 'retired')),
            target_weight DOUBLE PRECISION
                CHECK(target_weight IS NULL OR (target_weight >= 0 AND target_weight <= 1)),
            minimum_weight DOUBLE PRECISION
                CHECK(minimum_weight IS NULL OR (minimum_weight >= 0 AND minimum_weight <= 1)),
            maximum_weight DOUBLE PRECISION
                CHECK(maximum_weight IS NULL OR (maximum_weight >= 0 AND maximum_weight <= 1)),
            effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            effective_until TIMESTAMPTZ,
            rationale TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(mandate_version_id, target_id),
            CHECK(effective_until IS NULL OR effective_until >= effective_from),
            CHECK(minimum_weight IS NULL OR maximum_weight IS NULL OR minimum_weight <= maximum_weight),
            CHECK(target_weight IS NULL OR minimum_weight IS NULL OR target_weight >= minimum_weight),
            CHECK(target_weight IS NULL OR maximum_weight IS NULL OR target_weight <= maximum_weight)
        )
    """)
    op.execute("CREATE INDEX idx_mandate_assignment_target ON mandate_target_assignment(target_id)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS mandate_target_assignment")
    op.execute("DROP TABLE IF EXISTS mandate_version")
    op.execute("DROP TABLE IF EXISTS capital_allocation_mandate")
    # Downgrade restores the old structure, not discarded prototype rows.
    op.execute("""
        CREATE TABLE objective (
            objective_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            objective_key TEXT NOT NULL UNIQUE,
            objective_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'draft'
                CHECK(status IN ('draft', 'active', 'paused', 'retired')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE TABLE objective_version (
            objective_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            objective_id BIGINT NOT NULL REFERENCES objective(objective_id),
            version_no INTEGER NOT NULL CHECK(version_no > 0),
            purpose TEXT NOT NULL,
            budget_amount NUMERIC(20, 2) NOT NULL CHECK(budget_amount >= 0),
            currency TEXT NOT NULL,
            target_return DOUBLE PRECISION,
            max_drawdown DOUBLE PRECISION,
            investment_horizon TEXT,
            execution_mode TEXT NOT NULL DEFAULT 'live',
            valid_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            valid_to TIMESTAMPTZ,
            change_reason TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(objective_id, version_no)
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_objective_current_version
        ON objective_version(objective_id) WHERE valid_to IS NULL
    """)
    op.execute("""
        CREATE TABLE objective_investment_target (
            objective_investment_target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            objective_version_id BIGINT NOT NULL REFERENCES objective_version(objective_version_id) ON DELETE CASCADE,
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            target_weight DOUBLE PRECISION NOT NULL,
            budget_cap NUMERIC(20, 2),
            rationale TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(objective_version_id, target_id)
        )
    """)
    op.execute("CREATE INDEX idx_objective_target_target ON objective_investment_target(target_id)")
