"""Add mandate operations, allocation weights, and capital budget history.

Revision ID: 0007_mandate_operations
Revises: 0006_mandate_review_cycle
"""

from alembic import op

revision = "0007_mandate_operations"
down_revision = "0006_mandate_review_cycle"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE capital_allocation_mandate_key_seq")
    op.execute("""
        SELECT setval(
            'capital_allocation_mandate_key_seq',
            COALESCE((SELECT MAX(mandate_id) FROM capital_allocation_mandate), 0) + 1,
            false
        )
    """)
    op.execute("""
        ALTER TABLE capital_allocation_mandate
        ALTER COLUMN mandate_key SET DEFAULT (
            'mandate-' || LPAD(nextval('capital_allocation_mandate_key_seq')::TEXT, 6, '0')
        )
    """)
    op.execute("""
        ALTER TABLE mandate_version
        ADD COLUMN allocation_weight DOUBLE PRECISION
        CHECK(allocation_weight IS NULL OR (allocation_weight >= 0 AND allocation_weight <= 1))
    """)
    op.execute("""
        ALTER TABLE mandate_version
        ADD CONSTRAINT ck_mandate_budget_source
        CHECK(allocation_weight IS NULL OR budget_amount IS NULL)
    """)
    op.execute("""
        CREATE TABLE capital_budget_version (
            capital_budget_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            version_no INTEGER NOT NULL UNIQUE CHECK(version_no > 0),
            total_budget NUMERIC(20, 2) NOT NULL CHECK(total_budget >= 0),
            currency TEXT NOT NULL CHECK(char_length(currency) = 3),
            effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            effective_until TIMESTAMPTZ,
            change_reason TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CHECK(effective_until IS NULL OR effective_until >= effective_from)
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_capital_budget_current_version
        ON capital_budget_version((effective_until IS NULL))
        WHERE effective_until IS NULL
    """)
    op.execute("""
        ALTER TABLE mandate_version
        DROP CONSTRAINT mandate_version_mandate_id_fkey
    """)
    op.execute("""
        ALTER TABLE mandate_version
        ADD CONSTRAINT mandate_version_mandate_id_fkey
        FOREIGN KEY (mandate_id) REFERENCES capital_allocation_mandate(mandate_id)
        ON DELETE CASCADE
    """)


def downgrade() -> None:
    op.execute("""
        ALTER TABLE mandate_version
        DROP CONSTRAINT mandate_version_mandate_id_fkey
    """)
    op.execute("""
        ALTER TABLE mandate_version
        ADD CONSTRAINT mandate_version_mandate_id_fkey
        FOREIGN KEY (mandate_id) REFERENCES capital_allocation_mandate(mandate_id)
    """)
    op.execute("DROP INDEX IF EXISTS uq_capital_budget_current_version")
    op.execute("DROP TABLE IF EXISTS capital_budget_version")
    op.execute("ALTER TABLE mandate_version DROP CONSTRAINT ck_mandate_budget_source")
    op.execute("ALTER TABLE mandate_version DROP COLUMN allocation_weight")
    op.execute("ALTER TABLE capital_allocation_mandate ALTER COLUMN mandate_key DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS capital_allocation_mandate_key_seq")
