"""Detach themes from the obsolete investment-bucket strategy table.

Revision ID: 0008_remove_legacy_strategy
Revises: 0007_mandate_operations
"""

from alembic import op

revision = "0008_remove_legacy_strategy"
down_revision = "0007_mandate_operations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE theme DROP COLUMN strategy_id")
    op.execute("DROP TABLE strategy")


def downgrade() -> None:
    op.execute("""
        CREATE TABLE strategy (
            strategy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            strategy_key TEXT NOT NULL UNIQUE,
            strategy_name TEXT NOT NULL,
            description TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        INSERT INTO strategy (strategy_key, strategy_name, description)
        VALUES ('unclassified', 'Unclassified', 'Legacy strategy classification was removed')
    """)
    op.execute("ALTER TABLE theme ADD COLUMN strategy_id BIGINT REFERENCES strategy(strategy_id)")
    op.execute("UPDATE theme SET strategy_id = (SELECT strategy_id FROM strategy WHERE strategy_key = 'unclassified')")
    op.execute("ALTER TABLE theme ALTER COLUMN strategy_id SET NOT NULL")
